name: report
on:
  workflow_run:
    workflows: [ci]
    types: [completed, requested]

jobs:
  report:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/report.js')
            await script({ github, context, core })
